# Generated by Django 3.1.3 on 2020-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_articles_anons'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='anons',
            field=models.CharField(default=2, max_length=200, verbose_name='Анонс'),
            preserve_default=False,
        ),
    ]
